// <auto-generated />
using System;
using FitnessCenter.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenter.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913065619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("FitnessCenter.Api.Domain.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastServicedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_equipment_serial");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RepairCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("SessionsPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_plans_name");

                    b.ToTable("membership_plans", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("DiscountLabel")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("GrossAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NetAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("payment_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_reference");

                    b.ToTable("payments", (string)null);

                    b.HasDiscriminator<string>("payment_type").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingSessions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("ix_subscriptions_member_status");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Goal")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("workout_programs", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("MemberId", "StartTime")
                        .HasDatabaseName("ix_sessions_member_start");

                    b.HasIndex("TrainerId", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_trainer_timeslot")
                        .HasFilter("\"Status\" = 'BOOKED'");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.CreditCardPayment", b =>
                {
                    b.HasBaseType("FitnessCenter.Api.Domain.Payment");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryMonthYear")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CREDIT_CARD");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.PromptPayPayment", b =>
                {
                    b.HasBaseType("FitnessCenter.Api.Domain.Payment");

                    b.Property<string>("PromptPayId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QrExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PROMPT_PAY");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Admin", b =>
                {
                    b.HasBaseType("FitnessCenter.Api.Domain.User");

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ADMIN");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Member", b =>
                {
                    b.HasBaseType("FitnessCenter.Api.Domain.User");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<double?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("MEMBER");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Trainer", b =>
                {
                    b.HasBaseType("FitnessCenter.Api.Domain.User");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Certifications")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("RatingAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialization")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TRAINER");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.MaintenanceRequest", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnessCenter.Api.Domain.Equipment", "Equipment")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Api.Domain.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Equipment");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Payment", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Api.Domain.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Subscription", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Api.Domain.MembershipPlan", "MembershipPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.WorkoutProgram", "WorkoutProgram")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutProgram", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.Member", "Member")
                        .WithMany("Programs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Api.Domain.Trainer", "Trainer")
                        .WithMany("Programs")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutSession", b =>
                {
                    b.HasOne("FitnessCenter.Api.Domain.Member", "Member")
                        .WithMany("Sessions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Api.Domain.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnessCenter.Api.Domain.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Subscription");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Equipment", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.MembershipPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.WorkoutProgram", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Member", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Programs");

                    b.Navigation("Sessions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessCenter.Api.Domain.Trainer", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
